[workspace]
resolver = "3"
members = [
	"examples/async-sqlite",
	"examples/cpu-count",
	"examples/gzip-stream",
	"examples/hello-world",
	"examples/tokio-fetch",
]

[workspace.dependencies.neon]
version = "1.2.0-alpha.0"
features = ["tokio"]

[profile.release]
lto = true
