[package]
name = "gzip-stream"
version = "0.1.0"
description = "Neon Stream Example"
license = "MIT"
edition = "2024"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
flate2 = "1"
neon.workspace = true
