[package]
name = "cpu-count"
version = "0.1.0"
description = "CPU Count"
license = "MIT"
edition = "2024"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
neon.workspace = true
num_cpus = "1"
