[package]
name = "neon-binary-example"
version = "0.1.0"
authors = ["David Herman <david.herman@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "neon_binary_example"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2"

[dependencies]
neon = "0.2"
cslice = "0.3.0"
