[package]
name = "async-sqlite"
version = "0.1.0"
description = "Neon Async SQLite"
license = "MIT"
edition = "2024"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
neon.workspace = true
rusqlite = "0.37.0"
