[package]
name = "threading-hint"
version = "0.1.0"
authors = ["Dave Herman <david.herman@gmail.com>"]
license = "Apache-2.0"
build = "build.rs"

[lib]
name = "threading_hint"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2"

[dependencies]
neon = "0.2"
num_cpus = "1.4.0"
